"""
SQLAlchemy ORM models for the AuditChain Content Engine.
"""

import enum
from datetime import datetime, date
from typing import Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Date,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


# ── Enums ──────────────────────────────────────────────────────────────────


class Platform(str, enum.Enum):
    LINKEDIN = "linkedin"
    TWITTER = "twitter"
    BLOG = "blog"


class ContentPillar(str, enum.Enum):
    AI_FAIRNESS = "AI fairness"
    REGULATORY_UPDATES = "regulatory updates"
    BLOCKCHAIN_TRUST = "blockchain trust"
    CASE_STUDIES = "case studies"
    BEHIND_THE_SCENES = "behind the scenes"


class ContentStatus(str, enum.Enum):
    DRAFT = "draft"
    PENDING_REVIEW = "pending_review"
    APPROVED = "approved"
    SCHEDULED = "scheduled"
    PUBLISHED = "published"
    REJECTED = "rejected"


# ── Models ─────────────────────────────────────────────────────────────────


class ContentCalendarEntry(Base):
    """
    Represents a row in the content-calendar.csv.
    Imported on startup; drives the content generation schedule.
    """

    __tablename__ = "content_calendar_entries"
    __table_args__ = (
        UniqueConstraint("entry_date", "platform", "topic", name="uq_calendar_entry"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    entry_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    topic: Mapped[str] = mapped_column(String(500), nullable=False)
    platform: Mapped[Platform] = mapped_column(Enum(Platform), nullable=False)
    content_pillar: Mapped[ContentPillar] = mapped_column(Enum(ContentPillar), nullable=False)
    is_generated: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # One calendar entry → one generated post
    generated_content: Mapped[Optional["GeneratedContent"]] = relationship(
        "GeneratedContent", back_populates="calendar_entry", uselist=False
    )

    def __repr__(self) -> str:
        return f"<CalendarEntry {self.entry_date} {self.platform} {self.topic[:40]}>"


class GeneratedContent(Base):
    """
    A piece of content generated by Claude.
    Goes through a review → approve → schedule → publish lifecycle.
    """

    __tablename__ = "generated_content"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    calendar_entry_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("content_calendar_entries.id"), nullable=True, index=True
    )
    platform: Mapped[Platform] = mapped_column(Enum(Platform), nullable=False)
    content_pillar: Mapped[ContentPillar] = mapped_column(Enum(ContentPillar), nullable=False)
    topic: Mapped[str] = mapped_column(String(500), nullable=False)

    # The raw content body (full text or JSON array of tweets)
    body: Mapped[str] = mapped_column(Text, nullable=False)

    # Platform-specific fields
    hashtags: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Comma-separated
    word_count: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    tweet_count: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)  # For threads

    # Source: calendar-driven or news-triggered rapid response
    source_type: Mapped[str] = mapped_column(String(50), default="calendar")
    news_item_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("news_items.id"), nullable=True
    )

    # Lifecycle
    status: Mapped[ContentStatus] = mapped_column(
        Enum(ContentStatus), default=ContentStatus.PENDING_REVIEW
    )
    reviewer_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    scheduled_for: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    published_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Buffer export tracking
    buffer_update_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # Claude generation metadata
    prompt_tokens: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    completion_tokens: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    model_used: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Relationships
    calendar_entry: Mapped[Optional["ContentCalendarEntry"]] = relationship(
        "ContentCalendarEntry", back_populates="generated_content"
    )
    news_item: Mapped[Optional["NewsItem"]] = relationship(
        "NewsItem", back_populates="generated_content"
    )
    engagement_metrics: Mapped[list["EngagementMetric"]] = relationship(
        "EngagementMetric", back_populates="content"
    )

    def __repr__(self) -> str:
        return f"<GeneratedContent id={self.id} {self.platform} status={self.status}>"


class NewsItem(Base):
    """
    A news article fetched from an RSS feed.
    May trigger a rapid-response content generation.
    """

    __tablename__ = "news_items"
    __table_args__ = (UniqueConstraint("url", name="uq_news_url"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    feed_name: Mapped[str] = mapped_column(String(200), nullable=False)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    url: Mapped[str] = mapped_column(String(2000), nullable=False, unique=True)
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    published_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Claude's relevance assessment
    relevance_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    relevance_reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    suggested_angle: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    is_rapid_response: Mapped[bool] = mapped_column(Boolean, default=False)
    is_processed: Mapped[bool] = mapped_column(Boolean, default=False)

    fetched_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # One news item → one generated rapid-response post
    generated_content: Mapped[Optional["GeneratedContent"]] = relationship(
        "GeneratedContent", back_populates="news_item"
    )

    def __repr__(self) -> str:
        return f"<NewsItem {self.feed_name}: {self.title[:50]}>"


class EngagementMetric(Base):
    """Stores platform engagement data when connected to social APIs."""

    __tablename__ = "engagement_metrics"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    content_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("generated_content.id"), nullable=False
    )
    platform: Mapped[Platform] = mapped_column(Enum(Platform), nullable=False)
    metric_date: Mapped[date] = mapped_column(Date, nullable=False)
    impressions: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    engagements: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    likes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    shares: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    comments: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    clicks: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    content: Mapped["GeneratedContent"] = relationship(
        "GeneratedContent", back_populates="engagement_metrics"
    )
