"""SendGrid email notifications for RegWatch alerts and reports."""
import logging
from datetime import datetime

import httpx

from app.config import settings
from app.models import RegulationItem, Report

logger = logging.getLogger(__name__)

SENDGRID_API_URL = "https://api.sendgrid.com/v3/mail/send"


def _sendgrid_headers() -> dict:
    return {
        "Authorization": f"Bearer {settings.sendgrid_api_key}",
        "Content-Type": "application/json",
    }


async def send_high_impact_alert(item: RegulationItem, recipients: list[str]) -> bool:
    """Send immediate email alert for HIGH impact items."""
    if not settings.sendgrid_api_key or not recipients:
        logger.warning("SendGrid not configured or no recipients, skipping email alert")
        return False

    import json

    try:
        action_items = json.loads(item.action_items or "[]")
    except json.JSONDecodeError:
        action_items = []

    action_html = (
        "<ul>" + "".join(f"<li>{a}</li>" for a in action_items) + "</ul>"
        if action_items
        else "<p><em>No action items.</em></p>"
    )

    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: #dc2626; color: white; padding: 16px; border-radius: 8px 8px 0 0;">
        <h2 style="margin: 0;">🚨 HIGH IMPACT Regulatory Alert</h2>
        <p style="margin: 4px 0 0 0;">RegWatch by AuditChain</p>
      </div>
      <div style="border: 1px solid #e5e7eb; padding: 24px; border-radius: 0 0 8px 8px;">
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 16px;">
          <tr>
            <td style="padding: 8px; font-weight: bold; width: 120px;">Region:</td>
            <td style="padding: 8px;">{item.region}</td>
          </tr>
          <tr style="background: #f9fafb;">
            <td style="padding: 8px; font-weight: bold;">Source:</td>
            <td style="padding: 8px;">{item.source_name}</td>
          </tr>
          <tr>
            <td style="padding: 8px; font-weight: bold;">Impact:</td>
            <td style="padding: 8px; color: #dc2626; font-weight: bold;">HIGH</td>
          </tr>
          <tr style="background: #f9fafb;">
            <td style="padding: 8px; font-weight: bold;">Published:</td>
            <td style="padding: 8px;">{item.published_at.strftime("%Y-%m-%d") if item.published_at else "Unknown"}</td>
          </tr>
        </table>

        <h3 style="margin-bottom: 8px;">
          <a href="{item.url}" style="color: #2563eb;">{item.title}</a>
        </h3>

        <h4 style="margin-bottom: 4px;">Summary</h4>
        <p style="color: #374151;">{item.ai_summary or "No summary available."}</p>

        <h4 style="margin-bottom: 4px;">Action Items for AuditChain</h4>
        {action_html}

        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
        <p style="font-size: 12px; color: #9ca3af;">
          This alert was generated by RegWatch, AuditChain's regulatory monitoring system.
          <a href="https://auditchain.ai/regwatch">Manage preferences</a>
        </p>
      </div>
    </body>
    </html>
    """

    payload = {
        "from": {
            "email": settings.sendgrid_from_email,
            "name": settings.sendgrid_from_name,
        },
        "subject": f"[RegWatch HIGH] {item.region}: {item.title[:80]}",
        "personalizations": [
            {"to": [{"email": r} for r in recipients]}
        ],
        "content": [{"type": "text/html", "value": html_body}],
    }

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                SENDGRID_API_URL,
                json=payload,
                headers=_sendgrid_headers(),
            )
            resp.raise_for_status()
            logger.info("Email alert sent for item %d to %d recipients", item.id, len(recipients))
            return True
    except Exception as exc:
        logger.error("Failed to send email alert for item %d: %s", item.id, exc)
        return False


async def send_report_email(
    report: Report,
    recipients: list[str],
    subject: str | None = None,
) -> bool:
    """Send a generated report (digest/newsletter) via SendGrid."""
    if not settings.sendgrid_api_key or not recipients:
        logger.warning("SendGrid not configured or no recipients, skipping report email")
        return False

    if not report.content_html:
        logger.warning("Report %d has no HTML content, skipping", report.id)
        return False

    email_subject = subject or report.title

    payload = {
        "from": {
            "email": settings.sendgrid_from_email,
            "name": settings.sendgrid_from_name,
        },
        "subject": email_subject,
        "personalizations": [
            {"to": [{"email": r} for r in recipients]}
        ],
        "content": [{"type": "text/html", "value": report.content_html}],
    }

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                SENDGRID_API_URL,
                json=payload,
                headers=_sendgrid_headers(),
            )
            resp.raise_for_status()
            logger.info(
                "Report email '%s' sent to %d recipients", report.title[:60], len(recipients)
            )
            return True
    except Exception as exc:
        logger.error("Failed to send report email for report %d: %s", report.id, exc)
        return False


async def send_newsletter_via_sendgrid_list(
    report: Report,
    list_id: str,
) -> bool:
    """Send monthly newsletter to a SendGrid contact list using Single Sends."""
    if not settings.sendgrid_api_key or not list_id:
        logger.warning("SendGrid list not configured, skipping newsletter send")
        return False

    now = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    # Create Single Send
    create_payload = {
        "name": f"RegWatch Newsletter — {report.title}",
        "send_to": {"list_ids": [list_id]},
        "email_config": {
            "subject": report.title,
            "html_content": report.content_html,
            "sender_id": 1,  # must be set via SendGrid UI / env
            "suppression_group_id": None,
        },
    }

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            # Create the single send
            create_resp = await client.post(
                "https://api.sendgrid.com/v3/marketing/singlesends",
                json=create_payload,
                headers=_sendgrid_headers(),
            )
            create_resp.raise_for_status()
            send_id = create_resp.json()["id"]

            # Schedule immediately
            schedule_resp = await client.put(
                f"https://api.sendgrid.com/v3/marketing/singlesends/{send_id}/schedule",
                json={"send_at": "now"},
                headers=_sendgrid_headers(),
            )
            schedule_resp.raise_for_status()
            logger.info("Newsletter sent via SendGrid single send ID: %s", send_id)
            return True
    except Exception as exc:
        logger.error("Failed to send newsletter: %s", exc)
        return False
