/**
 * PDF report generation service using PDFKit.
 * Produces a structured audit report with all findings.
 */

import PDFDocument from "pdfkit";
import { Readable } from "stream";
import { logger } from "../lib/logger";

interface AuditData {
  id: string;
  modelName: string;
  modelType: string;
  modelHash: string;
  trustScore: number | null;
  submittedAt: Date;
  completedAt: Date | null;
  fairnessResult: Record<string, unknown> | null;
  explainResult: Record<string, unknown> | null;
  robustResult: Record<string, unknown> | null;
  organization: { name: string; industry: string };
  certificate: { tokenId: number; txHash: string } | null;
}

/**
 * Generate a PDF audit report and return it as a readable stream.
 * The stream can be piped directly to an HTTP response for download.
 */
export async function generatePdfReport(audit: AuditData): Promise<Readable> {
  logger.info(`Generating PDF report for audit: ${audit.id}`);

  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const stream = doc as unknown as Readable;

  // ── Cover Page ────────────────────────────────────────────
  doc
    .fontSize(28)
    .fillColor("#1a1a2e")
    .text("AuditChain", { align: "center" });

  doc
    .fontSize(18)
    .fillColor("#4a4a8a")
    .text("AI Model Audit Report", { align: "center" });

  doc.moveDown(2);
  doc
    .fontSize(14)
    .fillColor("#333")
    .text(`Model: ${audit.modelName}`, { align: "center" })
    .text(`Organization: ${audit.organization.name}`, { align: "center" })
    .text(
      `Date: ${audit.completedAt?.toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }) ?? "In progress"}`,
      { align: "center" }
    );

  doc.addPage();

  // ── Trust Score ───────────────────────────────────────────
  doc.fontSize(20).fillColor("#1a1a2e").text("Overall Trust Score", { underline: true });
  doc.moveDown(0.5);

  const score = audit.trustScore ?? 0;
  const scoreColor = score >= 80 ? "#27ae60" : score >= 60 ? "#f39c12" : "#e74c3c";
  doc
    .fontSize(48)
    .fillColor(scoreColor)
    .text(`${score}/100`, { align: "center" });

  doc.moveDown();
  doc
    .fontSize(12)
    .fillColor("#666")
    .text(
      "The trust score is a weighted composite of fairness (35%), " +
        "explainability (25%), robustness (25%), and documentation quality (15%).",
      { align: "justify" }
    );

  // ── Audit Metadata ────────────────────────────────────────
  doc.addPage();
  addSection(doc, "Audit Metadata");
  addKeyValue(doc, "Audit ID", audit.id);
  addKeyValue(doc, "Model Name", audit.modelName);
  addKeyValue(doc, "Model Type", audit.modelType);
  addKeyValue(doc, "Model Hash (SHA-256)", audit.modelHash);
  addKeyValue(doc, "Organization", audit.organization.name);
  addKeyValue(doc, "Industry", audit.organization.industry);
  addKeyValue(doc, "Submitted At", audit.submittedAt.toISOString());
  addKeyValue(doc, "Completed At", audit.completedAt?.toISOString() ?? "N/A");

  if (audit.certificate) {
    addKeyValue(doc, "Certificate Token ID", String(audit.certificate.tokenId));
    addKeyValue(doc, "Certificate TX Hash", audit.certificate.txHash);
  }

  // ── Fairness Results ──────────────────────────────────────
  if (audit.fairnessResult) {
    doc.addPage();
    addSection(doc, "Fairness Analysis");
    addJsonSection(doc, audit.fairnessResult);
  }

  // ── Explainability Results ────────────────────────────────
  if (audit.explainResult) {
    doc.addPage();
    addSection(doc, "Explainability Analysis");
    addJsonSection(doc, audit.explainResult);
  }

  // ── Robustness Results ────────────────────────────────────
  if (audit.robustResult) {
    doc.addPage();
    addSection(doc, "Robustness Testing");
    addJsonSection(doc, audit.robustResult);
  }

  // ── Footer ────────────────────────────────────────────────
  doc.addPage();
  doc
    .fontSize(10)
    .fillColor("#999")
    .text(
      "This report was generated by AuditChain — an independent AI model auditing platform. " +
        "The findings in this report are based on automated analysis and should be reviewed " +
        "by qualified professionals.",
      { align: "justify" }
    );

  doc.end();
  return stream;
}

/** Add a section header */
function addSection(doc: PDFKit.PDFDocument, title: string): void {
  doc
    .fontSize(16)
    .fillColor("#1a1a2e")
    .text(title, { underline: true });
  doc.moveDown(0.5);
}

/** Add a key-value row */
function addKeyValue(doc: PDFKit.PDFDocument, key: string, value: string): void {
  doc
    .fontSize(11)
    .fillColor("#333")
    .text(`${key}: `, { continued: true })
    .fillColor("#555")
    .text(value);
}

/** Render JSON data as formatted text */
function addJsonSection(doc: PDFKit.PDFDocument, data: Record<string, unknown>): void {
  doc
    .fontSize(10)
    .fillColor("#444")
    .font("Courier")
    .text(JSON.stringify(data, null, 2), { lineGap: 2 });
  doc.font("Helvetica");
}
